# Generated by Django 4.2.16 on 2024-10-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_intra',
            field=models.BooleanField(default=False),
        ),
    ]
