# Generated by Django 4.2.16 on 2024-11-05 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_two_factor_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='two_factor_auth',
        ),
    ]
